name: 'Hello world'
description: 'Simple javascript hello world'
inputs:
  who-to-greet:
    description: 'Who to greet ?'
    required: true
    default: 'world'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
